const files=document.querySelector('#files'),process=document.querySelector('#process'),message=document.querySelector('#message'),list=document.querySelector('#documents'),drop=document.querySelector('#drop');
files.addEventListener('change',()=>{process.disabled=!files.files.length;drop.querySelector('strong').textContent=files.files.length?`${files.files.length} file(s) selected`:'Drop PDFs here'});
['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,()=>drop.classList.remove('drag')));
drop.addEventListener('drop',e=>{e.preventDefault();files.files=e.dataTransfer.files;files.dispatchEvent(new Event('change'))});
process.addEventListener('click',async()=>{process.disabled=true;message.textContent='Processing…';const form=new FormData();[...files.files].forEach(f=>form.append('files',f));form.append('schema_name','invoice');try{const r=await fetch('/api/v1/documents/batch',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.detail?.message||'Upload failed');message.textContent=`Accepted ${data.accepted.length}; rejected ${data.rejected.length}.`;await load()}catch(e){message.textContent=e.message}finally{process.disabled=false}});
document.querySelector('#refresh').addEventListener('click',load);
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
async function load(){const r=await fetch('/api/v1/documents');const docs=await r.json();if(!docs.length){list.innerHTML='<p class="empty">No documents yet. Upload a synthetic sample to begin.</p>';return}list.innerHTML=docs.map(d=>`<article class="doc"><div class="doc-head"><strong>${esc(d.filename)}</strong><span class="badge ${d.status}">${d.status.replace('_',' ')}</span></div><div class="meta"><span>${new Date(d.created_at).toLocaleString()}</span>${d.extraction?`<span>${Math.round(d.extraction.confidence*100)}% confidence</span><span>${d.extraction.text_method}</span>`:''}</div>${d.status==='completed'?`<div class="actions"><a href="/api/v1/documents/${d.id}/export.json">Download JSON</a><a href="/api/v1/documents/${d.id}/export.csv">Download CSV</a></div>`:''}${d.error_message?`<p>${esc(d.error_message)}</p>`:''}</article>`).join('')}
load();

